# See http://docs.spring.io/spring-boot/docs/current/reference/html/common-application-properties.html
spring:
  main:
    banner-mode: OFF

  data:
    mongodb:
      host: localhost
      port: 27017
  webflux:
    problemdetails:
      enabled: true